version: '3.8'

services:
  onesub:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "80:80"
    volumes:
      - data-volume:/app/backend/data
    restart: always

volumes:
  data-volume:
