services:
  onesub:
    image: congcong510/onesub:latest
    container_name: onesub
    networks:
      - nginx_network
    ports:
      - 5373:80
    volumes:
      - /tmp/zfsv3/nvme13/15246330601/data/Onesub/data:/app/backend/data
    restart: always
networks:
  nginx_network:
    external: true
