"""add_announcement_audit_login_setting_tables

Revision ID: 1e5098f50801
Revises: 4fa323b7ace6
Create Date: 2026-03-12 12:54:10.262482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e5098f50801'
down_revision: Union[str, Sequence[str], None] = '4fa323b7ace6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='公告标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='公告内容'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='公告类型: info/warning/success'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否显示'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(datetime('now', '+08:00'))"), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(datetime('now', '+08:00'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='操作人ID'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='操作人用户名'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='操作类型'),
    sa.Column('target_type', sa.String(length=50), nullable=True, comment='目标类型: user/order/plan/coupon/announcement/setting'),
    sa.Column('target_id', sa.String(length=50), nullable=True, comment='目标ID'),
    sa.Column('detail', sa.Text(), nullable=True, comment='操作详情'),
    sa.Column('ip', sa.String(length=50), nullable=True, comment='IP地址'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(datetime('now', '+08:00'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('login_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户ID（失败时可能为空）'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='登录用户名'),
    sa.Column('ip', sa.String(length=50), nullable=True, comment='登录IP'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='浏览器UA'),
    sa.Column('success', sa.Boolean(), nullable=False, comment='是否成功'),
    sa.Column('fail_reason', sa.String(length=200), nullable=True, comment='失败原因'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(datetime('now', '+08:00'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_logs_user_id'), 'login_logs', ['user_id'], unique=False)
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False, comment='配置键'),
    sa.Column('value', sa.Text(), nullable=True, comment='配置值'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='配置说明'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(datetime('now', '+08:00'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_settings_key'), 'site_settings', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_settings_key'), table_name='site_settings')
    op.drop_table('site_settings')
    op.drop_index(op.f('ix_login_logs_user_id'), table_name='login_logs')
    op.drop_table('login_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('announcements')
    # ### end Alembic commands ###
